export const GET_PRODUCTS_RESPONSE = "GET_PRODUCTS_RESPONSE";
export const GET_PRODUCT_RESPONSE = "GET_PRODUCT_RESPONSE";
export const ADD_NEW_PRODUCT_RESPONSE = "ADD_NEW_PRODUCT_RESPONSE";
export const UPDATE_EXISTING_PRODUCT_RESPONSE =
  "UPDATE_EXISTING_PRODUCT_RESPONSE";
export const DELETE_PRODUCT_RESPONSE = "DELETE_PRODUCT_RESPONSE";
export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_ERROR = "API_CALL_ERROR";
